# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0002_commenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenter',
            name='favorite',
            field=models.ManyToManyField(to='foodtruck.Foodtruck'),
        ),
    ]
