# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0004_reply_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
