# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0005_foodtruck_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
