# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0006_auto_20161117_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenter',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, to='foodtruck.Foodtruck'),
        ),
    ]
