# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0007_auto_20161113_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtruck',
            name='truck_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='truck_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodtruck.Foodtruck'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
