# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 01:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0008_auto_20161118_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
