# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodtruck', '0009_auto_20161118_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('T', 'Truck Driver'), ('A', 'User Account')], max_length=1)),
                ('favorite', models.ManyToManyField(blank=True, to='foodtruck.Foodtruck')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commenter',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='commenter',
            name='user',
        ),
        migrations.DeleteModel(
            name='Commenter',
        ),
    ]
