# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0010_auto_20161118_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
