# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0011_foodtruck_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtruck',
            name='address',
        ),
    ]
