# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodtruck', '0014_auto_20161120_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('truck_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtruck.Foodtruck')),
            ],
        ),
    ]
