# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0017_remove_foodtruck_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('T', 'Truck Driver'), ('A', 'User Account')], max_length=1),
        ),
    ]
