# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0018_auto_20161123_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
