# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0021_auto_20161124_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtruck',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='foodtruck',
            name='longitude',
        ),
    ]
