# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0023_profile_comment_profile_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_comment',
            old_name='truck_comment',
            new_name='profile_comment',
        ),
    ]
